import microsoft from "../../../assets/images/microsoftLogo.svg";
import google from "../../../assets/images/googleLogo.svg";
import amazon from "../../../assets/images/amazonLogo.svg";
import meta from "../../../assets/images/metaLogo.svg";

export const ROWS_DATA = [
    {
        id: 1,
        corporationName: "Microsoft Corporation",
        location: "Redmond, Washington, USA",
        employeeStrength: "2,00,000+",
        cmmLevel: "Level 5 : Optimizing",
        rating: 5,
        industryServed: ["software", "Gaming", "3+"],
        companyLogo: microsoft,
        isFavourite: true,
    },
    {
        id: 2,
        corporationName: "Google LLC (Alphabet Inc.)",
        location: "Mountain View, California, USA",
        employeeStrength: "1,80,000+",
        cmmLevel: "Level 5 : Optimizing",
        rating: 2,
        industryServed: ["Internet Services", "AI", "5+"],
        companyLogo: google,
        isFavourite: false,

    },
    {
        id: 3,
        corporationName: "Amazon.com, Inc",
        location: "Seattle, Washington, USA",
        employeeStrength: "1,50,000+",
        cmmLevel: "Level 5 : Optimizing",
        rating: 3,
        industryServed: ["E-commerce", "Logistics", "2+"],
        companyLogo: amazon,
        isFavourite: false,

    },
    {
        id: 4,
        corporationName: "Meta Platforms, Inc. ",
        location: "Menlo Park, California, USA",
        employeeStrength: "65,000+",
        cmmLevel: "Level 5 : Optimizing",
        rating: 4,
        industryServed: ["Social Media", "Social Media", "AR"],
        companyLogo: meta,
        isFavourite: true,

    },
];

export const FAVOURITES_VENDOR = [
    {
        id: 1,
        corporationName: "Microsoft Corporation",
        location: "Redmond, Washington, USA",
        employeeStrength: "2,00,000+",
        cmmLevel: "Level 5 : Optimizing",
        rating: 5,
        industryServed: ["software", "Gaming", "3+"],
        companyLogo: microsoft,
    },
    {
        id: 2,
        corporationName: "Google LLC (Alphabet Inc.)",
        location: "Mountain View, California, USA",
        employeeStrength: "1,80,000+",
        cmmLevel: "Level 5 : Optimizing",
        rating: 5,
        industryServed: ["Internet Services", "AI", "5+"],
        companyLogo: google,
    },
    {
        id: 3,
        corporationName: "Amazon.com, Inc",
        location: "Seattle, Washington, USA",
        employeeStrength: "1,50,000+",
        cmmLevel: "Level 5 : Optimizing",
        rating: 5,
        industryServed: ["E-commerce", "GamLogisticsing", "2+"],
        companyLogo: amazon,
    },
    {
        id: 4,
        corporationName: "Meta Platforms, Inc. ",
        location: "Menlo Park, California, USA",
        employeeStrength: "65,000+",
        cmmLevel: "Level 5 : Optimizing",
        rating: 5,
        industryServed: ["Social Media", "Social Media", "AR"],
        companyLogo: meta,
    },
];


export const COUNTRY_STATE_LIST = {
    "Australia": [
        "New South Wales",
        "Victoria",
        "Queensland",
        "Western Australia",
        "South Australia",
        "Tasmania"
    ],
    "India": [
        "Andhra Pradesh",
        "Arunachal Pradesh",
        "Assam",
        "Bihar",
        "Chhattisgarh",
        "Goa",
        "Gujarat",
        "Haryana",
        "Himachal Pradesh",
        "Jharkhand",
        "Karnataka",
        "Kerala",
        "Madhya Pradesh",
        "Maharashtra",
        "Manipur",
        "Meghalaya",
        "Mizoram",
        "Nagaland",
        "Odisha",
        "Punjab",
        "Rajasthan",
        "Sikkim",
        "Tamil Nadu",
        "Telangana",
        "Tripura",
        "Uttar Pradesh",
        "Uttarakhand",
        "West Bengal"
    ],
    "Germany": [
        "Baden-Württemberg",
        "Bavaria (Bayern)",
        "Berlin",
        "Brandenburg",
        "Bremen",
        "Hamburg",
        "Hesse (Hessen)",
        "Lower Saxony (Niedersachsen)",
        "Mecklenburg-Vorpommern",
        "North Rhine-Westphalia (Nordrhein-Westfalen)",
        "Rhineland-Palatinate (Rheinland-Pfalz)",
        "Saarland",
        "Saxony (Sachsen)",
        "Saxony-Anhalt (Sachsen-Anhalt)",
        "Schleswig-Holstein",
        "Thuringia (Thüringen)"
    ],
    "Singapore": [
        "Central Region",
        "East Region",
        "North Region",
        "North-East Region",
        "West Region"
    ],
    "USA": [
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming"
    ]
}
